name: CI/CD Solución Gym

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    # Este paso es el "login" con las credenciales que obtuviste de Azure
    - name: Iniciar sesión en Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Aquí Docker hará el build y el push automáticamente
    - name: Construir y Subir Imagen
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/gym-backend:latest ./backend
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/gym-backend:latest