# Etapa 1: Construcción (Build)
FROM node:20-alpine AS builder

WORKDIR /app

# Copiamos solo los archivos de dependencias para aprovechar el cache de Docker
COPY package*.json ./
RUN npm install

# Copiamos el resto del código y compilamos
COPY . .
RUN npm run build

# Etapa 2: Producción (Ejecución)
FROM node:20-alpine

WORKDIR /app

# Copiamos solo lo estrictamente necesario de la etapa anterior
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# NestJS suele correr en el 3000 por defecto
EXPOSE 3000

CMD ["node", "dist/main"]